# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3d3c6bb3ee41933b06f6394154bb43fac0028fa87d710b9c77e9f698155c5e5458ce81dcf8370bdc6a3dd9b09efa6fe9fa03001a9cde1a004a7d554c7e338ab

test:
  secret_key_base: aa51cd9de35c11ee44232a56ef1d4c3d403cdeb33f1fc8a237b4d5b108cde032f7073b3de72990c5b77576d6794087389c632fd59145eeec6c106d5600508116

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
